#!/bin/bash
# Job name:
#SBATCH --job-name=hp_ca
#
# Project:
#SBATCH --account=nn2849K
#
# Wall clock limit:
#SBATCH --time='72:00:00'
#
# Max memory usage per task:
#SBATCH --mem-per-cpu=4000M
#
# Number of tasks (cores):
#SBATCH --ntasks=8

## Set up job environment
source /cluster/bin/jobsetup
module load openmpi.gnu

## Set up input and output files:
cp *.dat $SCRATCH
cp cuboid_mpi $SCRATCH
cp param $SCRATCH
#chkfile "output*"
cleanup "cp -r $SCRATCH/output* $SUBMITDIR/"

cd $SCRATCH
mpirun -np 8  ./cuboid_mpi
