#!/bin/bash
# Job name:
#SBATCH --job-name=hp_ca
#
# Project:
#SBATCH --account=nn2849K
#
# Wall clock limit:
#SBATCH --time='72:00:00'
#
# Max memory usage per task:
#SBATCH --mem-per-cpu=4000M
#
# Number of tasks (cores):
#SBATCH --ntasks=64

## Set up job environment
source /cluster/bin/jobsetup
module load hdf5/1.8.12_intel 

## Set up input and output files:
cp *.dat $SCRATCH
cp "cuboid_mpi${SUFFIX}" $SCRATCH
cp param $SCRATCH
#chkfile "output*"
#SUFFIX=_kd0.7
cleanup "cp -r $SCRATCH/output* $SUBMITDIR/RyR${SUFFIX}_normal/"

cd $SCRATCH
mpirun  "./cuboid_mpi${SUFFIX}"
